version: "3.9"
services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-admin:latest
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - TZ=${TZ:-America/New_York}
      - AUTH_SECRET=${AUTH_SECRET:-n6WKAuaUVdOYMRReNYXEd/sHLF/Ddfams+FAGMe7vzk=}
      - AUTH_TRUST_HOST=${ADMIN_DOMAIN:-app.hacado.com}
      - BETTER_AUTH_URL=https://${ADMIN_DOMAIN:-app.hacado.com}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
      - SHORT_DOMAIN=${SHORT_DOMAIN:-haca.do}
      - SMS_LINK_SHORTENING_ENABLED=${SMS_LINK_SHORTENING_ENABLED:-false}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.hacado.com}
      - APPS_EXTERNAL_DOMAIN=${APPS_EXTERNAL_DOMAIN:-apps.hacado.com}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - RESEND_OAUTH_CLIENT_ID=${RESEND_OAUTH_CLIENT_ID:-}
      - RESEND_OAUTH_CLIENT_SECRET=${RESEND_OAUTH_CLIENT_SECRET:-}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      - TEXTBELT_API_KEY=${TEXTBELT_API_KEY}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - "./apps/admin/public/upload:/app/public/upload"
    networks:
      - hacado-network
    depends_on:
      - mongodb
      - redis
      - job-processor
      - notification-sender

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-web:latest
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - TZ=${TZ:-America/New_York}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.hacado.com}
      - APPS_EXTERNAL_DOMAIN=${APPS_EXTERNAL_DOMAIN:-apps.hacado.com}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - RESEND_OAUTH_CLIENT_ID=${RESEND_OAUTH_CLIENT_ID:-}
      - RESEND_OAUTH_CLIENT_SECRET=${RESEND_OAUTH_CLIENT_SECRET:-}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./apps/web/public/upload:/app/public/upload"
    networks:
      - hacado-network
    depends_on:
      - mongodb
      - redis
      - job-processor
      - notification-sender
      - admin

  notification-sender:
    build:
      context: .
      dockerfile: apps/notification-sender/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-notification-sender:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.hacado.com}
      - APPS_EXTERNAL_DOMAIN=${APPS_EXTERNAL_DOMAIN:-apps.hacado.com}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - RESEND_OAUTH_CLIENT_ID=${RESEND_OAUTH_CLIENT_ID:-}
      - RESEND_OAUTH_CLIENT_SECRET=${RESEND_OAUTH_CLIENT_SECRET:-}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-smtp}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_SECURE=${SMTP_SECURE:-true}
      - SMTP_EMAIL=${SMTP_EMAIL:-hacado@example.com}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Hacado}
      - SMTP_AUTH_USER=${SMTP_AUTH_USER:-hacado@example.com}
      - SMTP_AUTH_PASS=${SMTP_AUTH_PASS:-"secure_password"}
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - RESEND_EMAIL=${RESEND_EMAIL:-}
      - RESEND_FROM_NAME=${RESEND_FROM_NAME:-Hacado}
      - RESEND_CUSTOMER_EMAIL=${RESEND_CUSTOMER_EMAIL:-}
      - RESEND_CUSTOMER_FROM_NAME=${RESEND_CUSTOMER_FROM_NAME:-}
      - TEXTBELT_API_KEY=${TEXTBELT_API_KEY}
      - SHORT_DOMAIN=${SHORT_DOMAIN:-haca.do}
      - SMS_LINK_SHORTENING_ENABLED=${SMS_LINK_SHORTENING_ENABLED:-false}
    restart: unless-stopped
    networks:
      - hacado-network
    depends_on:
      - mongodb
      - redis

  job-processor:
    build:
      context: .
      dockerfile: apps/job-processor/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-job-processor:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.hacado.com}
      - APPS_EXTERNAL_DOMAIN=${APPS_EXTERNAL_DOMAIN:-apps.hacado.com}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - RESEND_OAUTH_CLIENT_ID=${RESEND_OAUTH_CLIENT_ID:-}
      - RESEND_OAUTH_CLIENT_SECRET=${RESEND_OAUTH_CLIENT_SECRET:-}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    networks:
      - hacado-network
    depends_on:
      - mongodb
      - redis

  app-external-server:
    build:
      context: .
      dockerfile: apps/app-external-server/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-app-external-server:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.hacado.com}
      - APPS_EXTERNAL_DOMAIN=${APPS_EXTERNAL_DOMAIN:-apps.hacado.com}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - RESEND_OAUTH_CLIENT_ID=${RESEND_OAUTH_CLIENT_ID:-}
      - RESEND_OAUTH_CLIENT_SECRET=${RESEND_OAUTH_CLIENT_SECRET:-}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - SQUARE_APP_WEBHOOK_SIGNATURE_KEY=${SQUARE_APP_WEBHOOK_SIGNATURE_KEY}
      - SQUARE_ENVIRONMENT=${SQUARE_ENVIRONMENT:-sandbox}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - TEXTBELT_API_KEY=${TEXTBELT_API_KEY}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "5556:5556"
    networks:
      - hacado-network
    depends_on:
      - mongodb
      - redis

  domain-checker:
    build:
      context: .
      dockerfile: apps/domain-checker/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-domain-checker:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
    restart: unless-stopped
    ports:
      - "5555:5555"
    networks:
      - hacado-network
    depends_on:
      - mongodb

  link-shortener:
    build:
      context: .
      dockerfile: apps/link-shortener/Dockerfile
    image: ghcr.io/dbondarchuk/hacado-link-shortener:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/hacado?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-hacado.me}
      - SHORT_DOMAIN=${SHORT_DOMAIN:-haca.do}
      - MARKETING_URL=${MARKETING_URL:-https://hacado.com}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.hacado.com}
      - PORT=5557
    restart: unless-stopped
    ports:
      - "5557:5557"
    networks:
      - hacado-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    #command: mongod --replSet rs0
    # healthcheck:
    #   test: |
    #     mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
    #   start_period: 0s
    #   interval: 500ms
    #   timeout: 5s
    #   retries: 5
    ports:
      - "27017:27017"
    networks:
      - hacado-network
    volumes:
      - mongodb-data:/data/db
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hacado-network
    volumes:
      - redis-data:/data

networks:
  hacado-network:
    driver: bridge
volumes:
  redis-data:
  mongodb-data:
