import { Footer } from "@/components/web/footer/Footer";
import { Header } from "@/components/web/header/Header";
import type { Metadata } from "next";
import { Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import { TwLoad } from "./twLoad";
import { Toaster } from "@/components/ui/toaster";

export const dynamic = "force-dynamic";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${playfair.variable} scroll-smooth`}
    >
      <TwLoad />
      <body>
        <Header />
        <main className="min-h-screen bg-white pt-20 prose-lg lg:prose-xl prose-h3:text-4xl max-w-none font-body">
          {children}
        </main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
