import {
  AlertTriangle,
  ArrowRight,
  Blocks,
  Brush,
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Code2,
  Cog,
  Command,
  CreditCard,
  File,
  FileText,
  Globe,
  HelpCircle,
  Image,
  Instagram,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Mail,
  MailSearch,
  MessageCircle,
  Moon,
  MoreVertical,
  Paintbrush,
  PanelBottom,
  PanelTop,
  Paperclip,
  Pizza,
  Plus,
  Send,
  Settings,
  SunMedium,
  Trash,
  User,
  User2Icon,
  UserX2Icon,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  appointments: CalendarClock,
  cog: Cog,
  social: Instagram,
  smtp: Mail,
  header: PanelTop,
  footer: PanelBottom,
  assets: Paperclip,
  pages: Globe,
  sms: MessageCircle,
  script: Code2,
  communicationLogs: MailSearch,
  paintbrush: Paintbrush,
  brush: Brush,
  app: Blocks,
  communications: Send,
};
