import { IAssetsService } from "./assets.service";
import { ICommunicationLogsService } from "./communication-logs.service";
import { IConfigurationService } from "./configuration.service";
import { IConnectedAppsService } from "./connected-apps.service";
import { ICustomersService } from "./customers.service";
import { IEventsService } from "./events.service";
import { INotificationService } from "./notification.service";
import { IPagesService } from "./pages.service";
import { IPaymentsService } from "./payments.service";
import { IScheduleService } from "./schedule.service";
import { IServicesService } from "./services.service";
import { ITemplatesService } from "./templates.service";

export * from "./assets.service";
export * from "./communication-logs.service";
export * from "./configuration.service";
export * from "./connected-apps.service";
export * from "./customers.service";
export * from "./events.service";
export * from "./notification.service";
export * from "./pages.service";
export * from "./payments.service";
export * from "./schedule.service";
export * from "./services.service";
export * from "./templates.service";

export type IServicesContainer = {
  ConfigurationService: () => IConfigurationService;
  AssetsService: () => IAssetsService;
  EventsService: () => IEventsService;
  PagesService: () => IPagesService;
  CustomersService: () => ICustomersService;
  ServicesService: () => IServicesService;
  ScheduleService: () => IScheduleService;
  TemplatesService: () => ITemplatesService;
  CommunicationLogsService: () => ICommunicationLogsService;
  ConnectedAppsService: () => IConnectedAppsService;
  NotificationService: () => INotificationService;
  PaymentsService: () => IPaymentsService;
};
